name: Lint & Unit Test
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [dev]
jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [14.19, 16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install -g codecov && pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm test && codecov
