name: Unit Test

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14.19.0, 16.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
